### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by mrahhal** [atifaziz/NCrontab#12]
Any plans for supporting .NET Core?

**Comment by atifaziz** [comment]
@mrahhal Last time I checked (before RC2, that is), it just worked as NCrontab is already a PCL targeting a profile that was supported by .NET Core. Are you seeing an issue?

**Comment by mrahhal** [comment]
I didn't really try using the PCL (I think it should work). But what I mean is supporting a `netstandard` TFM. I don't think the support for PCLs in .NET Core would go away but it would be really great if a `netstandard` version is available (so that I don't have to play with `imports` for now).

You might want to do that anyway, I mean switching to `project.json`. It can build to all target platforms from one project instead of having to work with 2 project files (a normal .csproj + a pcl).

**Comment by atifaziz** [comment]
Since the PCL is a workable option, it seems wasteful to spend time right now targeting RC2 when the tooling remains preview. [`.xproj` and `project.json`](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) is going away so I'd rather let the dust settle there and do the migration in one shot. What's more, moving the project to preview tooling would exclude other people who are not living on the bleeding edge from building the project and potentially contributing.

Maintaining two project files isn't ideal but it's done so the pain isn't there.

I'm going to close this issue because the PCL package means NCrontab technically supports .NET Core. Feel free to demonstrate it's not the case and we can revisit.

**Comment by mrahhal** [comment]
Nope, forgot some people are still waiting for RTM (especially the tooling) so it makes sense to stay like this for now as long as it works :+1:
I'm going to try the PCL and let you know if everything works as expected.

**Comment by mrahhal** [comment]
@atifaziz works great if I add the following:

```diff
 "netstandard1.5": {
   "imports": [
     "dnxcore50",
+    "portable-net45+netcore45+wpa81+wp8"
   ],
   "dependencies": {
     "NETStandard.Library": "1.5.0-rc2-24027"
   }
 }
```

**Comment by atifaziz** [comment]
@mrahhal Thanks for dropping and reporting that! 👍

**Comment by atifaziz** [comment]
Re-opening now that .NET Core 1.x is out.

Plan is to not require [importing via a PCL profile](https://github.com/atifaziz/NCrontab/issues/12#issuecomment-225998017) as well as building using `dotnet` CLI.

**Comment by atifaziz** [comment]
NCrontab is now available as a [.NET Standard](https://docs.microsoft.com/en-us/dotnet/articles/standard/library) 1.0 library with [release 3.3](https://github.com/atifaziz/NCrontab/releases/tag/v3.3).
