### ISSUE TITLE
Issue with get occurrences by N number of days 

### ISSUE THREAD

**Issue by apatel2848** [atifaziz/NCrontab#52]
Is there a way to get occurrences of every N number of days without resetting to a month?  

For example, 0 0 0 1/7 * ? for the beginning date of 09-10-2019 will give occurrences every 7 days until end of September but next date of occurrence will start on October 1st instead of continuing from the last occurrence date of September.

Result:
09-15-2019
09-22-2019
09-29-2019
10-01-2019
10-08-2019
10-15-2019

How to achieve result:
09-15-2019
09-22-2019
09-29-2019
10-06-2019
10-13-2019
10-20-2019

**Comment by atifaziz** [comment]
I am afraid not because `1/7` means every 7th day of the starting from the 1st of that month. If you checkout what [crobtab guru has to say for `0 0 1/7 * *`](https://crontab.guru/#0_0_1/7_*_*), it reads, “At 00:00 on every 7th day-of-month from 1 through 31.” If you click the _next_ link to ask for a sample of next occurrences, you'll see that it's consistent with NCrontab:

![image](https://user-images.githubusercontent.com/20511/64685757-c9a1ac00-d487-11e9-989d-12b1bc2ec7ee.png)
