### ISSUE TITLE
Strong-name assembly

### ISSUE THREAD

**Issue by atifaziz** [atifaziz/NCrontab#8]
Please sign the ncrontab assembly in nuget! I'm currently signing and maintaining my own version because I need to reference it in a signed assembly. Thanks :)

---
Originally reported on Google Code with ID 8

Reported by @phrosty on 2013-06-27 21:54:38

**Comment by mathewc** [comment]
Funny, I was just coming to your repo to log this same bug. We really need this as well. We're using this awesome library in several important projects, and we can't sign our assemblies because yours is not signed. E.g. https://github.com/Azure/azure-webjobs-sdk-extensions/issues/41

Is this something you can do soonish? :)

**Comment by atifaziz** [comment]
[Published to NuGet](https://www.nuget.org/packages/ncrontab.signed/). Please note that this assembly is named `NCrontab.Signed` to distinguish and [avoid conflicts](https://github.com/davidebbo/WebActivator/wiki/Signing-WebActivator#why-not-just-create-a-new-major-version-without-changing-the-packageassembly-name) with the unsigned version.

**Comment by mathewc** [comment]
Thanks for the quick turn around! So you'll be publishing both a signed and unsigned package in step going forward?

**Comment by atifaziz** [comment]
@mathewc Yes, that's plan. They are 100% identical except in name (i.e. `NCrontab.Signed` vs `NCrontab`) and that one is strong-named and the other not so it doesn't look like too much trouble to keep them in step.
